### ISSUE TITLE
Crashes on user-changed-contents

### ISSUE THREAD

**Issue by pyluyten** [xuchunyang/bijiben#2]
gsignal.c:2462: signal 'user-changed-contents' is invalid for instance '0x1eddf00' of type 'BijiWebkitEditor'

**Comment by pyluyten** [comment]
(gdb) bt
#0  0x00000030f938c989 in JSStringGetMaximumUTF8CStringSize () from /lib64/libjavascriptcoregtk-3.0.so.0
#1  0x000000000042c44c in on_selection_got (object=<optimized out>, result=<optimized out>, user_data=0xe4d2b0)
    at editor/biji-webkit-editor.c:492
#2  0x00000030f168286b in g_task_return_now (task=0xe54ee0 [GTask]) at gtask.c:1076
#3  0x00000030f1682ee6 in g_task_return (task=0xe54ee0 [GTask], type=<optimized out>) at gtask.c:1129
#4  0x00007ffff5dd8808 in webkitWebViewRunJavaScriptCallback () from /lib64/libwebkit2gtk-3.0.so.25
#5  0x00007ffff5e5dba8 in WebKit::WebPageProxy::scriptValueCallback () from /lib64/libwebkit2gtk-3.0.so.25
#6  0x00007ffff5f4a52f in WebKit::WebPageProxy::didReceiveMessage () from /lib64/libwebkit2gtk-3.0.so.25
#7  0x00007ffff7370ff0 in IPC::MessageReceiverMap::dispatchMessage () from /lib64/libwebkit2gtk-3.0.so.25
#8  0x00007ffff5e76d7b in WebKit::WebProcessProxy::didReceiveMessage () from /lib64/libwebkit2gtk-3.0.so.25
#9  0x00007ffff736a064 in IPC::Connection::dispatchMessage () from /lib64/libwebkit2gtk-3.0.so.25
#10 0x00007ffff736a1d0 in IPC::Connection::dispatchOneMessage () from /lib64/libwebkit2gtk-3.0.so.25
#11 0x00000030f983bcc3 in WTF::RunLoop::performWork () from /lib64/libjavascriptcoregtk-3.0.so.0
#12 0x00000030f9849009 in WTF::RunLoop::queueWork () from /lib64/libjavascriptcoregtk-3.0.so.0
#13 0x0000003056849c3a in g_main_dispatch (context=0x6a3000) at gmain.c:3064
#14 g_main_context_dispatch (context=context@entry=0x6a3000) at gmain.c:3663
#15 0x0000003056849f88 in g_main_context_iterate (context=context@entry=0x6a3000, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at gmain.c:3734
#16 0x000000305684a03c in g_main_context_iteration (context=0x6a3000, context@entry=0x0, may_block=may_block@entry=1) at gmain.c:3795
#17 0x00000030f16a5894 in g_application_run (application=0x6a91a0 [Bijiben], argc=argc@entry=1, argv=argv@entry=0x7fffffffde98)
    at gapplication.c:2114
#18 0x0000000000417406 in main (argc=1, argv=0x7fffffffde98) at bjb-main.c:37
(gdb)
